microsoft/azuredevopslabs

- labs/vsts/powerbi/readme.md
Adding powerbi deprecated note.
> adding deprecated note

- _data/sidebars/tfs.yml
> sidebarfix

- labs/vstsextend/aspnetmodernize/readme.md
add missing "." in the COPY command. the right sample should be 
```
FROM microsoft/aspnet:4.7.1-windowsservercore-ltsc2016
ARG source
WORKDIR /inetpub/wwwroot
COPY ${source:-obj/Docker/publish} .
```
> Update docker file content

- _layouts/default.html
- labs/azuredevops/agile/readme.md
- labs/azuredevops/continuousdeployment/readme.md
- labs/azuredevops/continuousintegration/readme.md
- labs/azuredevops/deliveryplans/readme.md
- labs/azuredevops/exploratorytesting/readme.md
- labs/azuredevops/git/readme.md
- labs/azuredevops/github-integration/readme.md
- labs/azuredevops/load/readme.md
- labs/azuredevops/packagemanagement/readme.md
- labs/azuredevops/sonarcloud/readme.md
- labs/azuredevops/testmanagement/readme.md
- labs/azuredevops/wiki/readme.md
- labs/azuredevops/yaml/readme.md
Hi Sachin,
I have added Rating Widget for Getting started labs. Please verify.
Thanks
Balaji
> adding rating widget for getting started labs

- labs/tfs/agile/readme.md
- labs/tfs/agileworkitems/readme.md
- labs/tfs/appinsights/readme.md
- labs/tfs/armtemplates/readme.md
- labs/tfs/aspnetazure/readme.md
- labs/tfs/build/readme.md
- labs/tfs/codeanalysis/readme.md
- labs/tfs/codedui/readme.md
- labs/tfs/debugging/readme.md
- labs/tfs/deliveryplans/readme.md
- labs/tfs/devexp/readme.md
- labs/tfs/devteamcollaboration/readme.md
- labs/tfs/editorconfig/readme.md
- labs/tfs/exploratorytesting/readme.md
- labs/tfs/git/readme.md
- labs/tfs/intellitest/readme.md
- labs/tfs/intellitrace/readme.md
- labs/tfs/livedependencyvalidation/readme.md
- labs/tfs/liveunittesting/readme.md
- labs/tfs/manualtesting/readme.md
- labs/tfs/packagemanagement/readme.md
- labs/tfs/releasemanagement/readme.md
- labs/tfs/snapshotdebugger/readme.md
- labs/tfs/sqlprompt/readme.md
- labs/tfs/technicaldebt/readme.md
- labs/tfs/vsproductivity/readme.md
- readme.md
Hi Sachin,
I have updated Technet Lab links for TFS labs. Please verify.
Thanks
Balaji
> updated Technet Lab links for TFS Labs

- _includes/head.html
Hi Sachin,
We have added Linked In insights tag to the site. Please verify.
Thanks
Balaji
> adding LinkedIn pixel

- .gitignore
Change to ignore local VS config folder.
> Ignore .vs folder

- labs/vstsextend/aml/Readme.md
@sriramdasbalaji Added the author name as discussed on email
> doc: Added author name

- labs/vstsextend/github-azurepipelines/readme.md
Should work as-is for copy/paste into a project
> Cleaned up YAML

- labs/vstsextend/sonarcloud/readme.md
Branding article from VSTS to AzureDevOps
> Branding Azure DevOps

- labs/devopsserver/debugging/readme.md
Was Debugging, should be Debug
> Fixed misspelled menu option

- labs/azuredevops/continuousdeployment/readme.md
- labs/azuredevops/pullrequests/readme.md
Made some minor content updates to improve the lab experience.
Continuous Deployment 
- It was easy to miss the checkbox for Allow Azure Services to access server. Made a small change to call it out in the instructions as well.
Pull Requests
- If a user proceeded to another lab they would run into some issues when they went to edit the master branch as instructed by the labs. Added a note at the bottom to reverse the changes once complete.
> Minor Content Updates

- labs/azuredevops/github-integration/readme.md
Fixing a typo found while teaching DevOps class.
> Quick typo fix  "get you own" --> "get your own"

- labs/azuredevops/pullrequests/readme.md
fixed a typo (changed marge to merge)
> Updated readme,md by fixing a typo

- labs/vstsextend/appcenter/README.md
Updated link to App Center sign up page.
> Updated link to App Center sign up page

- labs/vstsextend/kubernetes/armtemplate/azuredeploy.json
Hi team,
I've just updated the file to have the latest version of kubernetes, otherwise the template fails validation. It's better to have it here than to edit the template every time we want to deploy it.
> Updated template file to add current version of kubernetes

- labs/vstsextend/kubernetes/armtemplate/azuredeploy.json
- Default k8s version
- ACR Api version
- ACR Login Server version
> Updated versions

- labs/vstsextend/selenium/readme.md
> Documentation improvements

- labs/vstsextend/terraform/readme.md
Changed "once the build success" to once the build succeeds"
> Corrected typo

- labs/azuredevops/yaml/readme.md
Was following the lab and noticed it had an extra `s` on this step. This PR removes that extra character. Linked issue of #523
> Removes extra character

- labs/vstsextend/ansible/readme.md
> Fixed broken link

- labs/tfs/readme.md
The existing links points now to a website hosting inappropriate content. Replaced it to a link to our documentation.
> ⚠️  Remove inappropriate links in our documentation

- labs/azure/jenkinscicd/README.md
https://github.com/microsoft/azuredevopslabs/blob/master/labs/azure/jenkinscicd/README.md 
#PingMSFTDocs
> Typo "Azure database for MYSQL"→"Azure Database for MySQL"
